"""admore models, started relationships, updated seeds

Revision ID: 77468b6eb89e
Revises: c52e9ed68348
Create Date: 2024-01-22 10:59:18.910574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77468b6eb89e'
down_revision = 'c52e9ed68348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_milestones_goal_id_goals')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestones')
    # ### end Alembic commands ###
