"""added another join table

Revision ID: 87972485c34f
Revises: 756e5d0fc44c
Create Date: 2024-01-22 11:07:36.483705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87972485c34f'
down_revision = '756e5d0fc44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_milestone_exercises_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_milestone_exercises_milestone_id_milestones')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestone_exercises')
    # ### end Alembic commands ###
