"""bruh

Revision ID: da54e7b2e307
Revises: e66694aa2300
Create Date: 2024-01-25 21:21:56.582119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da54e7b2e307'
down_revision = 'e66694aa2300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_workouts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exercise_workouts_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_exercise_workouts_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
